model_name: large
language: zh
device: cuda  # 或 "cpu"
buffer_seconds: 8
step_seconds: 2
remove_trailing_period: true
trailing_punctuation: ""   # 留空表示删除
punctuation_mode: "half"     # 或 "full"
model_cache_path: "models"  # 自定义模型存储路径
model_name: "iic/SenseVoiceSmall"  # 新增模型名称配置